### ISSUE TITLE
/swagger-yaml throws internal server error when running with build files

### ISSUE THREAD

**Issue by MrSharpp** [ad-on-is/adonis-autoswagger#76] opened 2024-04-16 12:22 UTC
when i try to access /docs which calls /swagger-yml on develop it works fine but it doesnt with build files
that request fails with 500 with this console output

```[12:21:10.079] ERROR (2932): ENOENT: no such file or directory, open '...\adonis-bug-rep\build\app\models\pom'
    request_id: "rrgltxnqc2pogpkh1g23yzc4"
    x-request-id: "rrgltxnqc2pogpkh1g23yzc4"
    err: {
      "type": "Error",
      "message": "ENOENT: no such file or directory, open '...\\adonis-bug-rep\\build\\app\\models\\pom'",
      "stack":
          Error: ENOENT: no such file or directory, open '...\adonis-bug-rep\build\app\models\pom'
      "errno": -4058,
      "code": "ENOENT",
      "syscall": "open",
      "path": "...\\adonis-bug-rep\\build\\app\\models\\pom",
      "status": 500
    }
```

Reproduceable Repo: https://github.com/MrSharpp/adonis-bug-rep

**Comment by MrSharpp** [comment] 2024-04-16 12:26
I guess it's most probably because the swagger endpoint shouldn't be available in prod build files, maybe thats why it's throwing 500. 
my fix would be to just omit /docs or /swagger-yml on build files.

**Comment by ad-on-is** [comment] 2024-04-16 12:29
Dupe of https://github.com/ad-on-is/adonis-autoswagger/issues/75
Just fixed in 3.12.0

**Comment by MrSharpp** [comment] 2024-04-16 12:43
did the same in the given steps in docs, the issue is same.
you can try the reproduceable repository which i added.

ENOENT: no such file or directory....

i dont know why it trying to access models & other folders without the js extension, if i remove the js extension it shows error for the next file

**Comment by ad-on-is** [comment] 2024-04-16 13:18
Is your NODE_ENV set to "production"?

**Closed** 2024-04-16 16:06 UTC
